AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 instances and specify network. 
Parameters: 
  SecurityGroupList:

  SubnetId:

  InstanceType:

  Environment:

  InstanceName:

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: <INSTANCE TYPE>
      ImageId: ami-090fa75af13c156b4
      SecurityGroupIds: <SECURITY GROUP>
      SubnetId: <SUBNET ID>
      Tags:
        - Key: Name
          Value: <INSTANCE NAME>
        - Key: Environment
          Value: <ENVIRONMENT NAME>
